### ISSUE TITLE
Web Design 2- Flex boxes

### ISSUE THREAD

**Issue by ShaylynHM** [ShaylynHM/flexible-info-card#1]
@thatkidmadrid
@wendywarren

Hey teach! I don't know if I am understanding this Flexbox thing, or at least putting it into use. I think my confusion might be in the selectors. Can you help clarify and/ or help me understand why my spacing is so messed up? I can't get it close enough for Markbot to pass. :(
Thanks
<img width="1393" alt="Screen Shot 2021-09-19 at 8 22 45 PM" src="https://user-images.githubusercontent.com/77545465/133948050-e46660d9-0102-4cb7-a039-3c96ab98786f.png">
<img width="801" alt="Screen Shot 2021-09-19 at 8 23 15 PM" src="https://user-images.githubusercontent.com/77545465/133948051-787bdb5c-390e-41f6-a339-624011bbdf30.png">
![Screen Shot 2021-09-19 at 8 23 52 PM](https://user-images.githubusercontent.com/77545465/133948052-a15c371c-deb3-42f0-9fea-dcaf08b26eae.png)

**Comment by thatkidmadrid** [comment]
Hey Shaylyn,

Looks like you have the colours all right and the basic layout, but something that may be making things more complicated than they should be is setting the `display:flex` on a lot of the components

[flexbox-cheat-sheet](https://learn-the-web.algonquindesign.ca/topics/flexbox-cheat-sheet/)
Take a look at the cheat sheet and you will remember that the `display: flex` should be used on the parent to have it's descendants become flexible.

[flexible-info-card](https://learn-the-web.algonquindesign.ca/courses/web-design-2/week-01/#flexible-info-card)
Also, some of the widths in the activity details hints may help get the layout that markbot is looking for, so I would take another look at those as well.

Hope that helps without giving away too much
